services:
  postgres:
    image: postgres:15.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}"
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - static_value:/app/static/
    env_file:
      - ./.env

  swag:
    image: lscr.io/linuxserver/swag
    depends_on:
      - backend
    cap_add:
      - NET_ADMIN
    environment:
      - URL="${DOMAIN}"
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      - EMAIL="${EMAIL}"
    volumes:
      - ./swag.conf:/config/nginx/site-confs/default.conf
      - static_value:/var/html/static/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

volumes:
  postgres_data:
  static_value:
    