services:

  postgres:
    image: postgres:15.2
    restart: always
    volumes:
      - bot_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../../.env

  backend:
    build: ../../
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - bot_static_value:/app/static/
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.23.3-alpine
    depends_on:
      - backend
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - bot_static_value:/var/html/static/

volumes:
  bot_postgres_data:
  bot_static_value:
