# CallBack Query data =======================================================
GET_AGE = "get_age"
GET_LOCATION = "get_location"
GET_COUNTRY = "get_country"
GET_REGION = "get_region"
GET_CITY = "get_city"
GET_FUND = "get_fund"
GET_FUNDS_INFO = "funds_info"
NO_FUND = "no_fund"
GET_NEW_FUND_FORM = "get_new_fund_form"
GET_NEW_MENTOR_FORM = "get_new_mentor_form"
SEND_SPREADSHEET = "send_spreadsheet"
GO_BACK = "go_back"

STACK = "stack"
