# CallBack Query data =======================================================
GET_AGE = "get_age"
GET_LOCATION = "get_location"
GET_COUNTRY = "get_country"
GET_REGION = "get_region"
GET_CITY_OR_AND_FUND = "get_what"
GET_CITY = "get_city"
GET_FUND = "get_fund"
GET_FUNDS_INFO = "funds_info"
NO_FUND = "no_fund"
GET_NEW_FUND_FORM = "new_fund"
GET_NEW_MENTOR_FORM = "ment"
SEND_SPREADSHEET = "send_spreadsheet"
GO_BACK = "go_back"
STACK = "stack"
